spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbs
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging.level:
  org.hibernate.SQL: debug

redis:
  host: localhost
  port: 6379

jwt:
  secret-key: jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4
  token-validity-in-sec: 300
  refresh-token-validity-in-sec: 604800

server:
  port: 8090

admin:
  ip: 127.0.0.1