CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  nickname CHAR(10) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS posts (
  post_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  views BIGINT DEFAULT 0,
  title VARCHAR(50) NOT NULL,
  content VARCHAR(10000) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  user_id BIGINT NOT NULL,
  nickname VARCHAR(10) NOT NULL,
  INDEX user_id_idx (user_id)
);